apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-app
  labels: 
    live: 4linux
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.27.2.3
    path: /srv/app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-volume-app
  labels: 
    live: 4linux
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  volumeName: volume-app

